export { HomePage } from "./HomePage";
export { ShopPage } from "./ShopPage";
export { ProductPage } from "./ProductPage";
export { CartPage } from "./CartPage";
export { CheckoutPage } from "./CheckoutPage";
export { LoginPage, SignupPage } from "./AuthPages";
export { ProfilePage } from "./ProfilePage";
export { OrdersPage } from "./OrdersPage";
export { PrivacyPage, TermsPage, ShippingPolicyPage, ReturnsPage } from "./LegalPages";
export { SizeGuidePage } from "./SizeGuidePage";
export { default as AdminPage } from "./AdminPage";
